# Generated by Django 3.0.2 on 2020-01-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('product_color', models.CharField(max_length=150)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('product_image', models.ImageField(upload_to='images')),
                ('product_avability', models.BooleanField(blank='True')),
            ],
        ),
    ]
